background_opacity	0.1

#font_family    FiraCode Nerd Font
font_family     Liga SFMono Nerd Font
#font_family     Ubuntu Nerd Font
#font_family      Noto Color Emoji
bold_font	auto
italic_font	auto
font_size 14.0

symbol_map U+276F Liga SFMono Nerd Font

symbol_map U+23FB-U+23FE,U+2600-U+26FF,U+2700-U+270D,U+1F000-U+1F9FF,U+1FA00-U+1FAFF Noto Color Emoji

#foreground                      #D8D1E0
foreground                      #E7E0F2
background                      #0D1117
selection_foreground            #0D1117
selection_background            #4B3D5B

cursor_shape    beam
cursor_beam_thickness   2.0
cursor                          #FF4E5E
cursor_text_color               #0D1117
cursor_trail    6
cursor_trail_decay 0.1 0.5

url_color                       #E05263

active_border_color             #FF4E5E
inactive_border_color           #1B263B
bell_border_color               #E05263

active_tab_foreground           #E05263
active_tab_background           #1B263B
inactive_tab_foreground         #4B3D5B
inactive_tab_background         #0D1117

color0  #0D1117
color1  #FF4E5E

#B38D92
color2  #E05263
color3  #947E9C
color4  #947E9C
#color5  #B58ECB
color5  #947E9C
color6  #1B263B

color7 #E7E0F2
#color7  #F2F0F5

color8  #947E9C
#color8  #A899A3
color9  #FF4E5E
color10 #E05263
color11 #947E9C
color12 #947E9C
color13 #947E9C
color14 #1B263B
color15 #E05263

window_padding_width 15
hide_window_decorations no
confirm_os_window_close 0
