font_family             FiraCode Nerd Font
font_size               14.0
background_opacity      0.60
window_padding_width    15
hide_window_decorations yes
confirm_os_window_close 0

foreground #e0d8d0
background #1a140f

selection_foreground #1a140f
selection_background #a89984

cursor            #e0d8d0
cursor_text_color background

url_color #b16286

active_border_color   #7c6f64
inactive_border_color #3c3836
bell_border_color     #913c44

active_tab_foreground   #1a140f
active_tab_background   #7c6f64
inactive_tab_foreground #d5c4a1
inactive_tab_background #3c3836
tab_bar_style           powerline

color0  #3c322b
color1  #9e3c50
color2  #a98e6a
color3  #d0a040
color4  #8f7a66
color5  #b16286
color6  #a89984
color7  #d5c4a1

color8  #928374
color9  #913c44
color10 #bfa98d
color11 #e8c67a
color12 #9d8a77
color13 #d65d0e
color14 #bdae93
color15 #e0d8d0
