background_opacity	0.65

font_family	MesloLGM Nerd Font
#font_family     JetBrainsMono Nerd Font
bold_font	auto
italic_font	auto

font_size 13.0


foreground #e8ddd4
background #2a2521
selection_foreground #2a2521
selection_background #d4c4b0


cursor #e8ddd4
cursor_text_color #2a2521


url_color #b8967a


active_border_color #8b6f5c
inactive_border_color #4a3f3a
bell_border_color #c94545


active_tab_foreground #e8ddd4
active_tab_background #4a3f3a
inactive_tab_foreground #a89080
inactive_tab_background #2a2521


color0 #2a2521
color1 #c94545
color2 #8b967a
color3 #d4b895
color4 #7a8b9a
color5 #a87a8b
color6 #7a9a8b
color7 #d4c4b0

color8  #4a3f3a
color9  #e85555
color10 #a5b28a
color11 #e8d4a5
color12 #8aa5b2
color13 #b88aa5
color14 #8ab2a5
color15 #f0e6d8

window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

