background_opacity	0.6

font_family	MesloLGM Nerd Font
#font_family	BlexMono Nerd Font
bold_font	auto
italic_font	auto

font_size 12.0

#background            #040F24

# stellar-deep style colors

foreground                      #c5c8c6
background                      #10121d
cursor                          #f0c674
selection_background            #373b41

color0                          #282a36
color1                          #cc6666
color2                          #33b58a
color3                          #f0c674
color4                          #81a2be
color5                          #b294bb
color6                          #8abeb7
color7                          #c5c8c6

color8                          #666666  
color9                          #d17b7b  
color10                         #43cfa1
color11                         #f8e3a9
color12                         #8eb4d5
color13                         #d3b9d7
color14                         #9cd9d1
color15                         #ffffff
