background_opacity	0.30

#font_family	BigBlueTerm437 Nerd Font Mono
#font_family	GohuFont 14 Nerd Font
#font_family	MesloLGM Nerd Font
font_family	BlexMono Nerd Font
bold_font	auto
italic_font	auto

font_size 13.0
