background_opacity	0.0
background_blur    200
# font_family    FiraCode Nerd Font
#font_family     Liga SFMonoNerdFont
#font_family     Comic Sans MS

#font_family      Noto Color Emoji
# bold_font	auto
# italic_font	auto
font_size 14.5

symbol_map U+23FB-U+23FE,U+2600-U+27BF,U+2900-U+297F,U+1F000-U+1F9FF,U+1FA00-U+1FAFF Noto Color Emoji

foreground                      #EADDD7
background                      #181615
selection_foreground            #F4F0EB
selection_background            #3E3834

cursor_shape            beam
cursor_beam_thickness   2.0
cursor                          #D4AF37
cursor_text_color               #181615

cursor_trail    10
cursor_trail_decay 0.1 0.5

url_color                       #247BA0

active_border_color             #FF8C42
inactive_border_color           #303035
bell_border_color               #FFE066

active_tab_foreground           #121214
active_tab_background           #FF8C42
inactive_tab_foreground         #E2E2E2
inactive_tab_background         #303035

color0  #322D29
color1  #A85A53
color2  #7A8964
color3  #C19B52
color4  #5D7B8C
color5  #926B7F
color6  #638E8A
color7  #D0C6BD

color8  #5A524C
color9  #C66D65
color10 #92A478
color11 #E5C07B
color12 #7698AD
color13 #B5879F
color14 #7BB0AB
color15 #F4F0EB

window_padding_width 15
hide_window_decorations no
confirm_os_window_close 0
allow_remote_control yes

# BEGIN_KITTY_FONTS
font_family      family="Monaco"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
