background_opacity	0.0
background_blur    100
#font_family    FiraCode Nerd Font
font_family     Liga SFMonoNerdFont
#font_family     Ubuntu Nerd Font
#font_family      Noto Color Emoji
bold_font	auto
italic_font	auto
font_size 14.5

symbol_map U+23FB-U+23FE,U+2600-U+27BF,U+2900-U+297F,U+1F000-U+1F9FF,U+1FA00-U+1FAFF Noto Color Emoji

foreground                      #CDD6F4
background                      #1E1E2E
selection_foreground            #1E1E2E
selection_background            #F5C2E7

cursor_shape            beam
cursor_beam_thickness   2.0
cursor                          #CBA6F7
cursor_text_color               #1E1E2E

cursor_trail    6
cursor_trail_decay 0.1 0.5

url_color                       #89B4FA

active_border_color             #CBA6F7
inactive_border_color           #313244
bell_border_color               #F9E2AF

active_tab_foreground           #11111B
active_tab_background           #CBA6F7
inactive_tab_foreground         #CDD6F4
inactive_tab_background         #181825

color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F5C2E7
color6  #94E2D5
color7  #BAC2DE

color8  #A6ADC8
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8

window_padding_width 15
hide_window_decorations no
confirm_os_window_close 0
