background_opacity	0.2

#font_family    FiraCode Nerd Font
font_family     Liga SFMonoNerdFont
#font_family     Ubuntu Nerd Font
bold_font	auto
italic_font	auto
font_size 14.0

foreground                      #D8D1E0
background                      #2A2226
selection_foreground            #2A2226
selection_background            #5E5164

cursor_shape    beam
cursor_beam_thickness   2.0
cursor                          #d9956a
cursor_text_color               #2A2226
cursor_trail    6
cursor_trail_decay 0.1 0.2

url_color                       #8396CD

active_border_color             #D9946A
inactive_border_color           #4A4147
bell_border_color               #E06B5C

active_tab_foreground           #D8D1E0
active_tab_background           #4A4147
inactive_tab_foreground         #6B5F69
inactive_tab_background         #2A2226

color0  #2A2226
color1  #E06B5C
color2  #B38D92
color3  #D9946A
color4  #8396CD
color5  #B58ECB
color6  #92B1C7
color7  #D8D1E0

color8  #6B5F69
color9  #F47F75
color10 #D1A7AF
color11 #F7B379
color12 #98AFF2
color13 #D1A5E8
color14 #A8C9E0
color15 #F2F0F5

window_padding_width 15
hide_window_decorations no
confirm_os_window_close 0
