font_family             FiraCode Nerd Font
font_size               14.0
background_opacity      0.50
window_padding_width    5
hide_window_decorations yes
confirm_os_window_close 0


foreground #d0b8a8
background #1a140f

selection_foreground #d0b8a8
selection_background #4a392e

cursor            #c0a090
cursor_text_color #1a140f

url_color #986c40

active_border_color   #9c7e68
inactive_border_color #6d5a4c
bell_border_color     #a85a6a

active_tab_foreground   #1a140f
active_tab_background   #9c7e68
inactive_tab_foreground #d0b8a8
inactive_tab_background #4a392e

color0  #3a2e25
color1  #bf4040
color2  #60a050
color3  #b89030
color4  #4080bf

#9050b0
color5  #8222b3
color6  #40a0a0
color7  #c0a898

#4a3930
color8  #5e4a3f
color9  #d85555
color10 #70c060
color11 #d0a040
color12 #5090d0

#a060c0
color13 #a54dd1
color14 #50b5b5
color15 #d0c0b0
