background_opacity 0.4

foreground #2d231e
background #f2e6dc
selection_foreground #f2e6dc
selection_background #614941

cursor #2d231e
cursor_text_color #f2e6dc

url_color #b58900

active_border_color #c8956d
inactive_border_color #b8a08c
bell_border_color #e85a8a

active_tab_foreground   #211a16
active_tab_background   #b8a08c
inactive_tab_foreground #614941
inactive_tab_background #e3d5c9

color0  #4a3832
color1  #c7254e
color2  #6a9052
color3  #b58900
color4  #517cad
color5  #965ea8
color6  #3a8a8a
color7  #2d231e

color8  #614941
color9  #d6305e
color10 #7cb26b
color11 #cf9f2b
color12 #5e8fcf
color13 #a86cc1
color14 #44a1a1
color15 #f7e8d6
