name: "Check for dead Markdown links"
on: [push]
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install markdown-link-check
      - name: Check for Markdown files
        id: check_files
        run: |
          if ! ls **/*.md 1> /dev/null 2>&1; then
            echo "No Markdown files found. Skipping link check."
            echo "found=false" >> $GITHUB_ENV
          else
            echo "found=true" >> $GITHUB_ENV
          fi
      - name: Run link check
        if: env.found == 'true'
        run: npx markdown-link-check **/*.md 
